### ISSUE TITLE
Why is the pull request being created as soon as I save some changes to a published resource?

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/campus#2]
Ok, this is a workflow question. I started playing with the CMS by correcting some mistakes in the XPath tutorial. I saved the changes. And as soon as I did (without touching SET STATUS —  which says 'Draft' or the Publish button), I got an email from vercel bot that the pull request is being automatically deployed with Vercel. 

And indeed, it is to be found here: https://github.com/stefanprobst/campus/pull/1

Questions:

1. Is there a way to delay the creation of the pull request until the user decides to perform an explicit action such as click on 'publish'? If not, we may end up getting a pull request on each save, which is less than ideal, because we'll never know if the contributor is still making changes or if they're done making changes and we should inspect and merge their pull request. 
2. Who is supposed to "set status"? The contributor or the editors? 
3. Does the status have any effect on what happens when somebody clicks on Publish?

All best,
Toma

**Comment by stefanprobst** [comment]
we need to enable `always_fork` option in the cms config
