### ISSUE TITLE
The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/campus#27]
Hey @stefanprobst 

I'm trying to install campus on my new laptop. Am I doing it correctly to run first `yarn install`?

When I do, I get this:

```
⋊> ~/D/s/campus on main ◦ yarn install                                  13:47:45
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
error campus@0.1.0: The engine "node" is incompatible with this module. Expected version "14.x". Got "16.2.0"
```

Now. do I need to downgrade my installation of node or would making campus compatible with 16.2 be something relatively easy?

**Comment by stefanprobst** [comment]
we're setting an explicit node version [here](https://github.com/stefanprobst/campus/blob/b00b0e66fb02481a87093dda9ea9e451dd1898a1/package.json#L34) for compatibility with vercel deployments (and, by extension, amazon AWS)

**Comment by stefanprobst** [comment]
so it's best to install node 14 locally - not sure about mac, but there are ways to quickly switch between currrently active node versions (like nvm or volta)

**Comment by stefanprobst** [comment]
check if this works on mac https://volta.sh/

**Comment by stefanprobst** [comment]
vercel/aws currentl support:

![vercel](https://user-images.githubusercontent.com/20753323/123258919-374f8880-d4f4-11eb-9bf7-f410319ce7f1.png)

**Comment by stefanprobst** [comment]
alternatively, we can remove the `engines` field from `package.json`

**Comment by ttasovac** [comment]
hey @stefanprobst 

i installed volta, it's super easy to set up. yarn install worked, but i get a build error which has something to do with the digital archives tag:

```
 Build error occurred
[Error: ENOENT: no such file or directory, open '/Users/ttasovac/Development/stefanprobst/campus/content/tags/digital-archives.yml'] {
  type: 'Error',
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/ttasovac/Development/stefanprobst/campus/content/tags/digital-archives.yml'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by ttasovac** [comment]
HA! i think you just pushed a fix for that

**Comment by stefanprobst** [comment]
yep i removed the "unused" tag but didn't realize it was used in one of the newly merged resources

**Comment by stefanprobst** [comment]
also pushed metadata caching just now
