### ISSUE TITLE
Publish new entry button

### ISSUE THREAD

**Issue by VickyGarnett** [stefanprobst/campus#28]
Hi Stefan - as discussed, the 'Publish New Entry' button that appears on the draft resources in the 'Workflow' page doesn't seem to be doing anything.  I assume it should!  

Screengrab of the button I mean is attached.

Thanks - V

![publish new entry button](https://user-images.githubusercontent.com/57193002/128323927-091eee5d-c1da-4105-9825-4993682db33a.png)

**Comment by stefanprobst** [comment]
this button is disabled, as with Open Authoring, content creators cannot publish content directly.

i agree this is not super obvious because the mouse cursor does seem to indicate that it's clickable (but that's mostly a problem of these UI elements only being visible on hover...

**Comment by VickyGarnett** [comment]
OK, I assume it's going to remain disabled in that case?  Can we remove it from view so as not to confuse/frustrate users?

**Comment by stefanprobst** [comment]
>  Can we remove it from view so as not to confuse/frustrate users?

not immediately (this is code not owned by us)

**Comment by stefanprobst** [comment]
note to self: styles are here: https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/components/Workflow/WorkflowCard.js#L84-L87

**Comment by VickyGarnett** [comment]
> > Can we remove it from view so as not to confuse/frustrate users?
> 
> not immediately (this is code not owned by us)

OK - in that case I'll explain this in the 'How-To' guide, and hopefully later we can change that :)

**Comment by stefanprobst** [comment]
best i could do is change the cursor to not look like a pointer
