### ISSUE TITLE
prettifying code in the preview 

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/campus#3]
code blocks look gorgeous in the rich-text version of the content —  but they should also be prettyfied in the preview on the right-hand side. 

at the moment they look like this:

<img width="1384" alt="Снимок экрана 2021-06-10 в 14 55 21" src="https://user-images.githubusercontent.com/5304839/121528597-e91e8d80-c9fb-11eb-8f5c-9a8229c748e2.png">

**Comment by stefanprobst** [comment]
the netlify CMS richtext editor uses codemirror for the codeblocks (as do we in the interactive Quiz editor). however, for the markdown codeblocks, we use shiki for syntax highlighting, which works great when prerendering at build time -- need to figure out how to include client bundle of shiki so we can use it to render code blocks in the cms preview pane

**Comment by stefanprobst** [comment]
this should now work.

we might want to select a subset of languages we want to support to avoid downloading all of them (they are cached, but nevertheless good idea i think) - keeping this issue open for now

**Comment by stefanprobst** [comment]
using the following list:

```json
[
  "css",
  "diff",
  "docker",
  "graphql",
  "java",
  "javascript",
  "js",
  "json",
  "jsx",
  "julia",
  "latex",
  "tex",
  "markdown",
  "md",
  "mdx",
  "perl",
  "php",
  "python",
  "py",
  "r",
  "shell",
  "bash",
  "sh",
  "sparql",
  "sql",
  "ssh-config",
  "svelte",
  "toml",
  "tsx",
  "turtle",
  "typescript",
  "ts",
  "vue",
  "wasm",
  "xml",
  "xsl",
  "yaml"
]
```
